# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --ci pulp_gem' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

.PHONY: format
format:
	black .

.PHONY: lint
lint:
	yamllint -s -d '{extends: relaxed, rules: {line-length: disable}}' .github/workflows
	bump-my-version bump --dry-run release
	black --check --diff .
	flake8
	check-manifest
	python .ci/scripts/check_requirements.py
	sh .ci/scripts/check_pulpcore_imports.sh
	sh .ci/scripts/check_gettext.sh
