# Generated by Django 4.2.1 on 2023-06-14 14:37

from django.db import migrations


def rename_gem_up(apps, schema_editor):
    Content = apps.get_model("core", "Content")
    Content.objects.filter(pulp_type="gem.gem").update(pulp_type="gem.shallow-gem")


def rename_gem_down(apps, schema_editor):
    Content = apps.get_model("core", "Content")
    Content.objects.filter(pulp_type="gem.shallow-gem").update(pulp_type="gem.gem")


class Migration(migrations.Migration):
    dependencies = [
        ("gem", "0004_alter_gemcontent_content_ptr_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GemContent",
            new_name="ShallowGemContent",
        ),
        migrations.RunPython(code=rename_gem_up, reverse_code=rename_gem_down, elidable=True),
    ]
