# Generated by Django 4.2.1 on 2023-06-14 14:53

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gem", "0005_rename_gemcontent_shallowgemcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="gemremote",
            name="excludes",
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
        migrations.AddField(
            model_name="gemremote",
            name="includes",
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
        migrations.AddField(
            model_name="gemremote",
            name="prereleases",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="GemContent",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("name", models.TextField()),
                ("version", models.TextField()),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                ("dependencies", django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ("required_ruby_version", models.TextField(null=True)),
                ("required_rubygems_version", models.TextField(null=True)),
                ("prerelease", models.BooleanField(default=False)),
            ],
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "unique_together": {("checksum",)},
            },
            bases=("core.content",),
        ),
    ]
