# Generated by Django 4.2.1 on 2023-07-31 15:14

from django.db import migrations, models

# This migration is believed to be safe for zero downtime upgrades.


class Migration(migrations.Migration):

    dependencies = [
        ('gem', '0007_DATA_fix_prerelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemcontent',
            name='platform',
            field=models.TextField(null=True),
        ),
    ]
