# Generated by Django 4.2.4 on 2023-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gem", "0010_delete_shallowgemcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gemcontent",
            name="platform",
            field=models.TextField(),
        ),
    ]
