# Generated by Django 4.2.4 on 2023-10-04 10:25

from django.db import migrations, models
import django.db.models.deletion
import pulpcore.app.util


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0110_apiappstatus"),
        ("gem", "0011_alter_gemcontent_platform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gemdistribution",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [
                    ("manage_roles_gemdistribution", "Can manage roles on gem distributions")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="gempublication",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [
                    ("manage_roles_gempublication", "Can manage roles on gem publications")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="gemremote",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [("manage_roles_gemremote", "Can manage roles on gem remotes")],
            },
        ),
        migrations.AlterModelOptions(
            name="gemrepository",
            options={
                "default_related_name": "%(app_label)s_%(model_name)s",
                "permissions": [
                    ("sync_gemrepository", "Can start a sync task"),
                    ("modify_gemrepository", "Can modify content of the repository"),
                    ("manage_roles_gemrepository", "Can manage roles on gem repositories"),
                    ("repair_gemrepository", "Can repair repository versions"),
                ],
            },
        ),
        migrations.AlterUniqueTogether(
            name="gemcontent",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="gemcontent",
            name="_pulp_domain",
            field=models.ForeignKey(
                default=pulpcore.app.util.get_domain_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.domain",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gemcontent",
            unique_together={("_pulp_domain", "checksum")},
        ),
    ]
